project:
  type: website
  output-dir: ../docs
  resources:
    - resume.pdf
    - projects/*
    - images/*
    - JaeHo_Bahng.png

website:
  title: "JaeHo Bahng"
  navbar:
    right:
      - href: index.qmd
        text: JaeHo Bahng
      - href: listing.qmd
        text: Projects

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full
    grid:
      body-width: 1000px
    



